### ISSUE TITLE
Lower case problems

### ISSUE THREAD

**Issue by nietoperz809** [EgonOlsen71/basicv2#4]
It would be better if the runtime system (not the basic prg itself) dispense with lower case letters.
They may look very ugly if the environment tries to mimic a true C64 screen. :)

**Comment by EgonOlsen71** [comment]
I've just added two additional methods to the PrintConsumer interface for splitting the output into program and system output. The system output defaults to upper case now. It's better this way anyway, because it allows for suppressing the actual system output completely if one doesn't want it for some reason.

**Comment by nietoperz809** [comment]
Thanks Egon. I've just copied the files to my project.
