### ISSUE TITLE
MoSpeed Frontend

### ISSUE THREAD

**Issue by jospic** [EgonOlsen71/basicv2#8]
Hello,
I'd like to build a multiplatform visual interface for MoSpeed. 
As for the compiler there are no problems because can use it from the command line. 
But, before compiling (.prg file) it would be useful to run the Basic interpreter to test the source code. 
There is a problem though: the VisualRuntime script not loading and running a file from command line. 
Is there any workaround? 
Thanks in advance.
-j

**Comment by EgonOlsen71** [comment]
You can run the interpreter from inside your code or via the (non-visual) Runner, which resides in the same package as the visual runtime. However, I'm not sure if this is actually feasible, because the interpreter isn't an emulator. Code that would run fine on the real machine after compilation might not run in the interpreter (or at least not as intended), because it's actually not a real C64, so at least POKES and PEEKS will not work as intended in the interpreter.

**Comment by jospic** [comment]
Yes, you have been very clear. 
I had already tried to run the Runtime.java, but it would only work for very simple code. 
Then, in addition to pure compilation, I might consider calling an emulator (Vice, etc) to run the source code. 
Obviously in the case of code with macro, like {clear}, etc, the emulator would give some error. 
However I will try to complete my project, for all platforms (Windows, Mac and Linux), to simplify the use of MOSpeed. 
Congratulations for the great job!
-j
